checks:
  addAllBuiltIn: true
  exclude:
    - default-service-account
    - no-anti-affinity
    - unset-cpu-requirements
    - no-read-only-root-fs
    - dangling-service
    - unset-memory-requirements
    - no-node-affinity
    - minimum-three-replicas
    - hpa-minimum-three-replicas
    - no-rolling-update-strategy
    - non-isolated-pod
    - required-label-owner
    - required-annotation-email
    - use-namespace
    - read-secret-from-env-var
    - env-var-secret
    - dnsconfig-options
    - no-liveness-probe
    - no-readiness-probe

customChecks: []
