replicaCount: 1

image:
  repository: localstack/localstack
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 4566
  targetPort: 4566

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

env:
  - name: DEBUG
    value: "0"
  - name: SERVICES
    value: "s3,secretsmanager"
  - name: DATA_DIR
    value: "/tmp/localstack/data"
  - name: HOST_TMP_FOLDER
    value: "/tmp/localstack"
  - name: PERSISTENCE
    value: "1"
  - name: DOCKER_HOST
    value: "unix:///var/run/docker.sock"

persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"

networking:
  externalAccess:
    enabled: true
    hostPort: 4566

services:
  s3:
    enabled: true
  secretsmanager:
    enabled: true