apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app: ollama
    component: ai-worker
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
    app: ollama
