{{- if .Values.components.nvidiaDevicePlugin.enabled }}
{{ include "nullnode.upstreamApp" (dict "root" $ "name" "nvidia-device-plugin" "component" .Values.components.nvidiaDevicePlugin) }}
{{- end }}
