{{- if .Values.components.observabilityStack.enabled }}
{{ include "nullnode.upstreamApp" (dict "root" $ "name" "kube-prometheus-stack" "component" .Values.components.observabilityStack) }}
{{- end }}
