{{- if .Values.components.externalSecretsConfig.enabled }}
{{ include "nullnode.localApp" (dict "root" $ "name" "external-secrets-config" "component" .Values.components.externalSecretsConfig) }}
{{- end }}
