apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "localstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "localstack.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: localstack
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: edge
          protocol: TCP
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /tmp/localstack/data
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "localstack.fullname" . }}-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
