apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: edge
  selector:
    {{- include "localstack.selectorLabels" . | nindent 4 }}
---
{{- if .Values.networking.externalAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}-external
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.networking.externalAccess.hostPort }}
    protocol: TCP
    name: edge
  selector:
    {{- include "localstack.selectorLabels" . | nindent 4 }}
{{- end }}