{{- if .Values.global.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "litellm.fullname" . }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
    release: {{ .Values.global.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      {{- include "litellm.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      honorLabels: true
{{- end }}
