apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
