apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
type: Opaque
stringData:
  master-key: {{ .Values.environment.LITELLM_MASTER_KEY }}
  salt-key: {{ .Values.environment.LITELLM_SALT_KEY }}
  database-url: {{ .Values.environment.DATABASE_URL }}
