{{- if and .Values.metrics.enabled .Values.global.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    release: {{ .Values.global.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 15s
{{- end }}
